### ISSUE TITLE
Bad things happen if you import webcomponents-lite after Polymer

### ISSUE THREAD

**Issue by notwaldorf** [webcomponents/shadydom#143]
Namely, this line throws: https://github.com/webcomponents/shadycss/blob/39eccced2c4001c96030bf97983d70a57ea10953/src/style-util.js#L243

(bad) Polymer -> WC -> elements: http://jsbin.com/lupopuc/1/edit?html
(good) WC -> Polymer -> elements: http://jsbin.com/qowaguhito/1/edit?html,output

**Comment by sorvell** [comment]
This occurs because ShadyCSS gets confused about whether native Shadow DOM is supported due to https://github.com/webcomponents/shadycss/blob/master/src/style-settings.js#L25. If this is run multiple times (which can happen if you separately load ScopingShim and ApplyShim for example), the setting is incorrect.
