### ISSUE TITLE
event patching not working on shadowRoot (removeEventListener)

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/shadydom#190]
event patching is not working properly for element shadowRoots, in particular event listeners aren't removed. e.g. See the following repro on Firefox http://jsbin.com/mizatey/2/edit?html,output
```js
var logger = function(event) { console.log('clicked!', event) };
var el = document.createElement('div');
el.attachShadow({mode: 'open'}).innerHTML = 'click me';
document.body.appendChild(el);
el.shadowRoot.addEventListener('click', logger);
el.shadowRoot.removeEventListener('click', logger);
```

Try clicking on the element and notice that `logger` keeps being invoked.

**Comment by sorvell** [comment]
@azakus It looks to me like the problem is where we [store the listener info](https://github.com/webcomponents/shadydom/blob/master/src/patch-events.js#L403) . We're always storing `this` as the target node, but this should be `target` which is specially set when we're listening on a shadowRoot. We do correctly pass this same specially set `target` when we try to [find the listener](https://github.com/webcomponents/shadydom/blob/master/src/patch-events.js#L447) in `removeEventListener`. Does that sound right?

**Comment by valdrinkoshi** [comment]
Verified the fix for the issue originally raised in https://github.com/vaadin/px-data-grid/issues/331 and it does fix it 👌

**Comment by talimarcus** [comment]
Any update on this?

**Comment by talimarcus** [comment]
Sweet, checked the fix with https://github.com/PolymerElements/iron-a11y-keys/issues/44 and it worked 👍 Can we get a tag for this please?
