### ISSUE TITLE
Element.prototype.querySelectorAll returns Array instead of NodeList in Firefox 61

### ISSUE THREAD

**Issue by TimvdLippe** [webcomponents/shadydom#254]
_From @Gugic on July 2, 2018 22:41_

Here is the simple jsbin:
http://jsbin.com/hoyecowadu/2/edit?html,console,output

In chrome console output will have NodeList (which is correct according to standards: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll). However in Firefox 61 (ubuntu linux/macos x) it will be simple Array of HtmlElement's

Removing of webcomponents-loader.js from page will make Firefox produce correct results (NodeList)

_Copied from original issue: webcomponents/webcomponentsjs#967_

**Comment by TimvdLippe** [comment]
This is an issue in shadydom: http://jsbin.com/qavaxenoxu/1/edit?html,console,output (you can comment the shadydom force to see the difference)

**Comment by Gugic** [comment]
Look fixed in last version
http://jsbin.com/zacohegufo/edit?html,console,output

**Comment by Gugic** [comment]
Any updates on this one?
For the context: it is breaking websites built with angular material 1.x, because in some places angular material is relying to NodeList functionality (dropdowns are being broken for sure)

**Comment by TimvdLippe** [comment]
This is a duplicate of #270 and is being worked on in #286

**Comment by morewry** [comment]
Is https://github.com/webcomponents/shadydom/pull/226 related?

**Comment by DRiFTy17** [comment]
@TimvdLippe Quick question for you regarding the `querySelectorAll` patch. I am running into a compatibility issue related to `querySelectorAll` returning an array instead of `NodeList`. I think this is the same thing mentioned by @Gugic above. A third-party library is using the `.item(index)` method on the result, and of course that is not there on an array type after the patch is applied.

I assume this was intentional, but would it be possible for you guys to return a "NodeList-Like" object that contains an `item()` method as well as the properties for each index so that it is compatible with both syntaxes?

Of course there is a performance impact with having to convert the array to an object, but it's likely negligible, and maybe that could be hidden behind a setting to use as needed? I'm just hoping that the patched native methods would return at least a similar API for these things for compatibility purposes.

**Comment by TimvdLippe** [comment]
@DRiFTy17 That method should exist on the polyfill already: https://github.com/webcomponents/shadydom/blob/4447ac74a917e4b04fec5327df8fb0a4c6b6ba2b/src/utils.js#L111-L113 (which was fixed in #226). I am not sure if QSA uses the same method. Could you open a PR with the fix if it does not?

**Comment by DRiFTy17** [comment]
@TimvdLippe Sure thing, I just opened PR #331 with this change and have validated that it also fixes the issue noted above by @Gugic with the angular material 1.x library.
