### ISSUE TITLE
Polyfill features needed for supported older browsers

### ISSUE THREAD

**Issue by sorvell** [webcomponents/shadydom#51]
e.g.
* Array.from: needed for Safari 7
* template: needed for IE11

**Comment by azakus** [comment]
`Array.from` is super easy to shim, but for `template`, we should probably split out the template polyfill from webcomponentsjs.

**Comment by Hotell** [comment]
@azakus I wouldn't call it easy at all https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill 

`Array.from` should be just replaced for something else in the context of it's usage. I don't think it's a good idea to polyfill ES6 features within ShadyDom lib, because if user already uses own polyfils he has to download the polyfiled code twice #perfmaters

**Comment by Hotell** [comment]
this https://github.com/webcomponents/shadydom/blob/c162774c0ad1ffe9f97c663ad2ffd27d5cd6ade9/src/element-mixin.js#L718 should be replaced probably with `[].slice.call()`

`let nodes = [].slice.call(mutation.addedNodes).filter(function(n) { .... })`

**Comment by sorvell** [comment]
Polyfilled via https://github.com/webcomponents/template and https://github.com/webcomponents/webcomponents-platform and more easily consumable by using https://github.com/webcomponents/webcomponentsjs.
