### ISSUE TITLE
assignedNodes() not working in connectedCallback()

### ISSUE THREAD

**Issue by cyrilletuzi** [webcomponents/shadydom#53]
> ShadyDOM distribution is asynchronous for performance reasons. This means that the composed dom will be available 1 microtask after the dom mutation occurs. For testing, ShadyDOM.flush may be called to force synchronous composition.

Due to this current limitation, calling `assignedNodes()` in the `connectedCallback()` of a custom element returns an empty array.

It's OK if I encapsulate the operation in a `setTimeout()`, but it's quite painful and a polyfill should follow the native behavior.

Is it possible to force `ShadyDOM.flush()` in the polyfilled `assignedNodes()` function ? If so, I can do a PR.

**Comment by sorvell** [comment]
This makes sense. It will require significant testing so a PR may be tricky. The call to `assignNodes` should probably do a `getRootNode()` and if that returns a `shadowRoot`, the shimmed `render` should be called on it.

**Comment by sorvell** [comment]
Sorry for the delay on this. This issue was addressed in https://github.com/webcomponents/shadydom/commit/a00a4b2d04931211fbc20ee712699620dfcc9a2a.

Here's a working example: http://jsbin.com/locehex/edit?html,output

It should be noted that a custom elements may not have children when `connectedCallback` is called. To see the `assignedNodes`, it's best to react to a `slotchange` event.
