### ISSUE TITLE
Refine element patching

### ISSUE THREAD

**Issue by sorvell** [webcomponents/shadydom#7]
There are a number of issues now with the element patching mechanism is implemented. For example:
- shadydom needs to snapshot the composed children when they have been parsed. There is not really a good spot to do this when used in conjunction with custom element lifecycle.
- patching currently does not extend up the tree to parents so that querySelector is properly scoped (correctness issue)
- patching too aggressively extends down the tree to all children unnecessarily (performance issue)

Likely patching will need to be split into a subset of api's: patch upward accessors (parentNode), patch downward visibility (querySelector), patch children (logical children).

**Comment by kevinpschaaf** [comment]
Additionally, appending a patched element to an unpatched spot fails, since the composed tree tracking information will fall out of sync.  This case (arising in similarly in https://github.com/Polymer/polymer/issues/3919 and https://github.com/Polymer/polymer/issues/4087) should be considered also.

One way would be to patch all `append`/insertBefore`/`replaceChild`/etc. methods on Node.prototype to ensure composed tree tracking on the target is maintained.

**Comment by sorvell** [comment]
Fixed via https://github.com/webcomponents/shadydom/pull/64.
