### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by matthewp** [webcomponents/shadydom#77]
This repository isn't being maintained currently. ☹️ I totally understand that people are busy and don't have time, I'm not admonishing *anyone*.  I would like to help out! And I know some other people in the web components community who might as well. Just reviewing and merging PRs at the very least.  

Paging @samuelli @justinfagnani as I know you two the best 🤠  Can we make this happen?

**Comment by lukasoppermann** [comment]
It would be awesome if a release would be possible faster, by having more people help here. Without at least one release, it makes it hard to use this polyfill as an option.

**Comment by justinfagnani** [comment]
This repo is actively being worked on. I see a few old PRs, is that the issue?

**Comment by matthewp** [comment]
Hey @justinfagnani, yes I've noticed that the repo is having some commits to it recently. As far as I can tell these all come from issues that Polymer has had (with releasing 2.0 I imagine?). Totally understandable as the main contributor is a member of the Polymer org. But with that being the case there are a number of PRs that haven't been merged or commented on.

I believe it would be better to have more maintainers of this project so that developers outside of Polymer can fix issues they are experiencing without taking resources away from Polymer development. In some cases there are issues that may very well not be relevant to Polymer (see my #70 as an example) but are blockers for other projects/usages. 

I completely want to be positive here, I'm very grateful for all of the great work that's been done here so far! I just think that with more community involvement we can push it forward faster. 🤝

**Comment by treshugart** [comment]
My time is currently limited getting Skate 5 closer to done but I'd be stoked to help out a little. I'm a WC org member, so I can help out with reviews maybe?

I think some of the barrier to entry here is that most of the contribs are coming from people on the Polymer team (please correct me if I'm wrong) so it sort of feels driven by that roadmap, or that there's an internal roadmap that may not be open to the public?

Either way, happy for people to ping me and ask for help.

**Comment by notwaldorf** [comment]
Hiya folks! Sorry for falling behind on the issues and PRs 😓. We really appreciate the work you're putting in, testing and giving feedback on the polyfill. Unfortunately, the team that's working on the polyfill is still really hard at work making it ready for use -- this is why we haven't tagged a release recently, because we're not comfortable it's in a spot where it won't be buggy. Even simple PRs take a fair bit of time to review, and with the upcoming deadline, there's just noone available to review them 🙁.

Give us a couple of weeks to get out of crunch mode, and we'll get back on track! ❤️

**Comment by matthewp** [comment]
@notwaldorf I have no deadlines I'm under. I volunteer to do the things that those on your team don't have time for right now. 🙂  That's why I created this thread, actually, to get more outside contributors with push access here.

**Comment by micahscopes** [comment]
I just read today that Google has a contributer license agreement they want people to sign before making pull requests. I wonder if that's showing things down? I actually didn't know about it until today, maybe there are others who do not know this and are making pull requests?

@matthewp, thanks for heading up the cloudydom fork. That's helpful!

**Comment by TimvdLippe** [comment]
@matthewp Sorry for the lack of replies. In the mean time, development should have caught up and there should be regular releases of the polyfill. I have been appointed to help out with triaging issues and responding more accurately to the various polyfill repositories.

If I look at the repository, it seems it is a lot more healthy and issues are responded to in shorter time. Is there anything else you would like to point out that we can improve upon? Thank you for your honest and valid feedback!

**Comment by matthewp** [comment]
This issue was always about expanding maintainers outside of Polymer contributors/core team. That it's healthy now isn't an indication of future health, given that all of the maintainers come from the same team that will have different priorities in the future (ex, when Polymer 3 is in crunch mode).

**Comment by sorvell** [comment]
We definitely welcome pull requests on the polyfill. Since it's fairly complex there haven't been a ton but we've definitely [merged](https://github.com/webcomponents/shadydom/pulls?q=is%3Apr+is%3Aclosed) a significant number of PR's from external devs.

@TimvdLippe has also [updated](https://github.com/webcomponents/shadydom/pull/200) the contribution guidelines, and that should make things more clear.

Going to close this since we've made significant progress on the core issue

**Comment by matthewp** [comment]
@sorvell I suggest reading the initial comment in this issue as your response has nothing to do with its contents. From my perspective there hasn't been any progress on the core issue, as Polymer team members are still the only with push access.
